platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '$(inherited)'
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '$PODS_ROOT/TensorFlowLiteSwift/Frameworks'
    end
  end

  # Add a build phase to copy the TFLite frameworks to the app bundle
  runner_target = installer.pods_project.targets.find { |target| target.name == 'Runner' }
  if runner_target
    tflite_build_phase = runner_target.new_shell_script_build_phase('Copy TFLite Frameworks')
    tflite_build_phase.shell_script = <<-'SHELL'
      TFLITE_FRAMEWORK_PATH="$PODS_ROOT/TensorFlowLiteSwift/Frameworks/TensorFlowLite.framework"
      TFLITE_BUNDLE_PATH="$PODS_ROOT/TensorFlowLiteSwift/Frameworks/TensorFlowLite.bundle"
      DEST_PATH="${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}"
      cp -r "$TFLITE_FRAMEWORK_PATH" "$DEST_PATH"
      cp -r "$TFLITE_BUNDLE_PATH" "$DEST_PATH"
    SHELL
  end
end
