name: vision_app
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.10.6
  tflite_flutter: ^0.10.4
  path_provider: ^2.1.4
  permission_handler: ^12.0.0
  shared_preferences: ^2.3.5
  provider: ^6.1.2
  http: ^1.1.0
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
